FROM eclipse-temurin:21-jdk-alpine
MAINTAINER gopakumar

# Copy and rename to auth-service.jar
COPY target/eureka-server-0.0.1-SNAPSHOT.jar eureka-server.jar

# Execute the file name
ENTRYPOINT ["java", "-jar", "/eureka-server.jar"]