FROM eclipse-temurin:21-jdk-alpine
MAINTAINER gopakumar

# Copy and rename to auth-service.jar
COPY target/ecommerce-0.0.1-SNAPSHOT.jar auth-service.jar

# Execute the file name
ENTRYPOINT ["java", "-jar", "/auth-service.jar"]
