FROM eclipse-temurin:21-jdk-alpine
MAINTAINER gopakumar

# Copy and rename to auth-service.jar
COPY target/user-service-0.0.1-SNAPSHOT.jar user-service.jar

# Execute the file name
ENTRYPOINT ["java", "-jar", "/user-service.jar"]
